base_urls:
    #- 'http://www.wflboces.org/component_districts.cfm'
    #- 'https://secure.myschooljobs.org/monroeboces2/owr.cfm?subpage=953454'
#    - 'http://www.bloomfieldcsd.org/'
#    - 'http://www.canandaiguaschools.org/home.cfm'
#    - 'http://www.clydesavannah.org/'
#    - 'http://dundeecs.org/'
#    - 'http://www.gananda.org/'
#    - 'http://www.genevacsd.org/'
#    - 'http://www.mwcsd.org/'
#    - 'http://www.honeoye.org/'
#    - 'http://www.lyonscsd.org/'
#    - 'http://www.redjacket.org/'
#    - 'http://www.marioncs.org/'
#    - 'http://www.naples.k12.ny.us/'
#    - 'http://www.newark.k12.ny.us/'
#    - 'http://www.nrwcs.org/'
#    - 'http://www.palmaccsd.org/'
#    - 'http://www.pycsd.org/'
#    - 'http://www.midlakes.org/'
#    - 'http://www.rccsd.org/'
#    - 'http://www.rcs.k12.ny.us/'
#    - 'http://www.sfcs.k12.ny.us/'
#    - 'http://www.soduscsd.org/'
#    - 'http://www.victorschools.org/'
#    - 'http://www.waterloocsd.org/'
#    - 'http://www.wayne.k12.ny.us/'
#    - 'http://www.williamsoncentral.org/'
    - 'http://dundeecs.org/jobs.cfm?location=0'
    - 'http://www.bcsd.org/jobs.cfm?cat=1'
    - 'http://www.canandaiguaschools.org/jobs.cfm?cat=6'
    - 'http://www.gananda.org/jobs.cfm?cat=1239'
    - 'http://www.genevacsd.org/jobs.cfm'
    - 'http://www.honeoye.org/district/job_opportunities/certified_positions/'
    - 'http://www.lyonscsd.org/jobs.cfm?location=0'
    - 'http://www.midlakes.org/departments.cfm?subpage=3662'
    - 'http://www.naples.k12.ny.us/jobs.cfm?location=0'
    - 'http://www.newarkcsd.org/page/455'
    - 'http://www.nrwcs.org/district.cfm?subpage=1198208'
    - 'http://www.pittsfordschools.org/jobs.cfm?location=0'
    - 'http://www.rccsd.org/jobs.cfm'
    - 'http://www.rcs.k12.ny.us/employment_opportunities/'
    - 'http://www.redjacket.org/district/employment_opportunities'
    - 'http://www.rhnet.org/jobs.cfm?cat=17'
    - 'http://www.sfcs.k12.ny.us/jobs.cfm?location=0'
    - 'http://www.soduscsd.org/jobs.cfm?location=818'
    - 'http://www.spencerportschools.org/jobs.cfm?cat=4'
    - 'http://www.spencerportschools.org/jobs.cfm?job=7790&cat=4&getjob=1'
    - 'http://www.waterloocsd.org/jobs.cfm'
    - 'http://www.williamsvillek12.org/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/ClydeSavannahCSD/jobs.cfm'
    - 'https://secure.myschooljobs.org/ClydeSavannahCSD/jobs.cfm?master=214293&cfm=end&school=0'
    - 'https://secure.myschooljobs.org/DansvilleCSD/jobs.cfm'
    - 'https://secure.myschooljobs.org/HolleyCSD/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/LeroyOWR/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/ManchesterShortsville/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/MarcusWhitmanCSD/jobs.cfm?cat=3617'
    - 'https://secure.myschooljobs.org/Marion/jobs.cfm?cat=3780'
    - 'https://secure.myschooljobs.org/Marion/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/MtMorris/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/NRWCSD/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/NewarkCSD/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/PennYan/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/bataviacsd/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/brockportcsd/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/churchvillechili/jobs.cfm?cat=490'
    - 'https://secure.myschooljobs.org/eirondequoit/jobs.cfm?cat=128'
    - 'https://secure.myschooljobs.org/erochester/jobs.cfm?cat=3234'
    - 'https://secure.myschooljobs.org/fairportcsd/jobs.cfm?cat=1595'
    - 'https://secure.myschooljobs.org/gananda/jobs.cfm?cat=3447'
    - 'https://secure.myschooljobs.org/gateschilicsd/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/greececsd/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/hflcsd/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/hilton/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/hornell/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/kendallcsd/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/kenton/jobs.cfm?cat=3368'
    - 'https://secure.myschooljobs.org/monroe1/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/monroeboces2/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/palmaccsd/jobs.cfm'
    - 'https://secure.myschooljobs.org/pennyan/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/victorcsd/jobs.cfm?cat=1496'
    - 'https://secure.myschooljobs.org/victorcsd/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/waynecsd/jobs.cfm?cat=715'
    - 'https://secure.myschooljobs.org/webster/jobs.cfm?cat=3544'
    - 'https://secure.myschooljobs.org/wflboces/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/wheatlandchili/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/williamsoncsd/jobs.cfm?cat=3599'
    - 'https://secure.myschooljobs.org/williamsoncsd/jobs.cfm?location=0'
    - 'https://secure.myschooljobs.org/wirondequoit/jobs.cfm?cat=2597'
    - 'https://secure.penfield.edu/jobs.cfm?location=0'
